name: my-xmonad
version: 0.1.0.0
synopsis: My highly configured Xmonad
description: See README
maintainer: Jacob Herbst <jacob@1362.dk>
# github: sol/hpack
category: Development
license: BSD3
build-type: Simple


ghc-options: -Wall #-Werror -threaded

source-dirs:
  - lib
  - .

dependencies:
  - base
  - containers
  - xmonad-contrib >= 0.17
  - xmonad >= 0.17
  - unix >= 2.7.2.2

library:
  source-dirs: lib
  exposed-modules:
    - Keybindings

executable:
  main: xmonad.hs
