resolver: lts-22.20

packages:
- .

extra-deps:
- xmonad-contrib-0.18.0@sha256:aae129651391ec65e4c7cf4c23b280cc5e69f709d86668502426a41eebab9d3c,22370

nix:
  enable: true
  pure: false
  packages:
    - gcc
    - cairo
    - gtk3-x11
    - pkg-config
    - xorg.libX11
    - xorg.libXft
    - xorg.libXScrnSaver
    - xorg.libXext
    - xorg.libXinerama
    - xorg.libXrandr
    - xorg.libXrender
    - xorg.libXdmcp
