module Theme where

black :: String
black         = "#282828";
red :: String
red           = "#cc241d";
green :: String
green         = "#98971a";
yellow :: String
yellow        = "#d79921";
blue :: String
blue          = "#458588";
magenta :: String
magenta       = "#b16286";
cyan :: String
cyan          = "#689d6a";
silver :: String
silver        = "#a89984";
grey :: String
grey          = "#928374";
brightred :: String
brightred     = "#fb4934";
brightgreen :: String
brightgreen   = "#b8bb26";
brightyellow :: String
brightyellow  = "#fabd2f";
brightblue :: String
brightblue    = "#83a598";
brightmagenta :: String
brightmagenta = "#d3869b";
brightcyan :: String
brightcyan    = "#8ec07c";
white :: String
white         = "#ebdbb2";
orange :: String
orange        = "#d65d0e";
brightorange :: String
brightorange  = "#fe8019";


bg :: String
bg = black
fg :: String
fg = white
panelbg :: String
panelbg = bg
panelfg :: String
panelfg = fg
border :: String
border = bg
error :: String
error = red
warning :: String
warning = yellow
highlight :: String
highlight = orange
