#!/usr/bin/env bash

is_active() {
    bluetoothctl show | grep "Powered" | cut -d' ' -f2
}

icon() {
    if [ "$(is_active)" == "yes" ]; then
        icon=""
    else
        icon=""
    fi
    printf "%s" "$icon"
}

toggle() {
    if [ "$(is_active)" == "yes" ]; then
        bluetoothctl power off > /dev/null
    else
        bluetoothctl power on > /dev/null
    fi
}

case $1 in
    toggle)
        toggle
        ;;
    *)
        icon
        ;;
esac
if [ "${EWW_UPDATE:-0}" == "1" ]; then
    eww update bluetooth_icon="$(icon)"
fi
